source 'http://rubygems.org'

ruby '2.5.3'

gem 'cucumber', '~>3.1.2'
gem 'graphql-client'
gem 'minitest'
gem 'gherkin'
gem 'json_spec'
gem 'syntax'
gem 'pry'
gem 'require_all'
gem 'hashdiff'
gem 'parseconfig'
gem 'docker-sync'
gem 'allure-cucumber', '0.6.1'
gem 'logger', '~> 1.3.0'
gem 'json-compare'
gem 'json-diff'
gem 'allure-ruby-adaptor-api'
gem 'rubysl-rexml', '~> 2.0', '>= 2.0.4'
gem 'gmail', '~> 0.7.1'
gem 'httpclient', '2.8.3'
gem 'rest-client'
